#! /usr/bin/env python 

import sys

def main():
	file = open(sys.argv[1], "r")
	file1 = open(sys.argv[2], "w")
	file2 = open(sys.argv[3], "w")
	out = file1

	for line in file:
		if line[0] == "-":
			out = file2
			continue
		out.write(line)
	file1.close()
	file2.close()

if __name__ == "__main__":
	if len(sys.argv) != 4:
		sys.stderr.write("partition: incorrect number of arguments\n")
		sys.exit(1)
	main()
